// <auto-generated />
using System;
using Book_Your_Hotel.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book_Your_Hotel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250429095434_OccupancyColumnAdded")]
    partial class OccupancyColumnAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book_Your_Hotel.Models.HotelNumbers", b =>
                {
                    b.Property<int>("HotelNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelNumber");

                    b.HasIndex("HotelID");

                    b.ToTable("HotelNumbers");
                });

            modelBuilder.Entity("Book_Your_Hotel.Models.Hotels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("int");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HotelLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "+977-9800000001",
                            CreatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://www.dotnetmastery.com/bluevillaimages/villa1.jpg",
                            Location = "Kathmandu, Nepal",
                            Name = "Luxury Palace",
                            NumberOfRooms = 150,
                            Occupancy = 0,
                            Price = 2000,
                            UpdatedOn = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "+977-9800000002",
                            CreatedOn = new DateTime(2024, 1, 2, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://www.dotnetmastery.com/bluevillaimages/villa2.jpg",
                            Location = "Solukhumbu, Nepal",
                            Name = "Everest View Resort",
                            NumberOfRooms = 80,
                            Occupancy = 0,
                            Price = 3690,
                            UpdatedOn = new DateTime(2024, 1, 2, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "+977-9800000003",
                            CreatedOn = new DateTime(2024, 1, 3, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://www.dotnetmastery.com/bluevillaimages/villa3.jpg",
                            Location = "Pokhara, Nepal",
                            Name = "Himalayan Bliss",
                            NumberOfRooms = 1400,
                            Occupancy = 0,
                            Price = 1150,
                            UpdatedOn = new DateTime(2024, 1, 3, 10, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            ContactNumber = "+91-9800000004",
                            CreatedOn = new DateTime(2024, 1, 4, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://www.dotnetmastery.com/bluevillaimages/villa4.jpg",
                            Location = "Goa, India",
                            Name = "Ocean View Hotel",
                            NumberOfRooms = 1200,
                            Occupancy = 0,
                            Price = 1180,
                            UpdatedOn = new DateTime(2024, 1, 4, 8, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            ContactNumber = "+971-9800000005",
                            CreatedOn = new DateTime(2024, 1, 5, 17, 20, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://www.dotnetmastery.com/bluevillaimages/villa5.jpg",
                            Location = "Dubai, UAE",
                            Name = "Desert Rose Inn",
                            NumberOfRooms = 250,
                            Occupancy = 0,
                            Price = 1500,
                            UpdatedOn = new DateTime(2024, 1, 5, 17, 20, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Book_Your_Hotel.Models.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("Book_Your_Hotel.Models.HotelNumbers", b =>
                {
                    b.HasOne("Book_Your_Hotel.Models.Hotels", "Hotels")
                        .WithMany()
                        .HasForeignKey("HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
